dist: xenial
language: node_js
node_js:
- "node"

cache:
  yarn: true

before_install:
- echo "Before install"

install:
- echo "Install"

before_script:
- npm install -g yarn
- yarn install
- yarn global add ionic cordova

script:
- ionic build

deploy:
  provider: pages
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  skip-cleanup: true
  keep-history: true
  repo: InfiniBrains/InfiniBrains.github.io
  target-branch: master
  on:
    branch: master
  local_dir: www