language: node_js
node_js:
— "node"

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - clang-5.0
    - gcc-6
    - g++-6
    - cmake

cache:
  yarn: true

before_script:
- npm install -g yarn
- npm install

