dist: xenial
language: node_js
node_js:
- "node"

compiler:
- clang

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - clang
    - gcc
    - g++
    - cmake

cache:
  yarn: true

before_install:
- echo "Before install"

install:
- echo "Install"

before_script:
- npm install -g yarn
- yarn install
- yarn global add ionic cordova

script:
- ionic cordova build browser --prod

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
#  keep-history: true
#  on:
#    branch: master
  local_dir: www